#pragma once

#define AGENT_SDK_VER_MAJOR 0
#define AGENT_SDK_VER_MINOR 0
#define AGENT_SDK_VER_PATCH 1

#define AGENT_SDK_TO_VERSION(major, minor, patch) (major * 10000 + minor * 100 + patch)
#define AGENT_SDK_VERSION AGENT_SDK_TO_VERSION(AGENT_SDK_VER_MAJOR, AGENT_SDK_VER_MINOR, AGENT_SDK_VER_PATCH)

#define AGENT_SDK_STRINGIFY_IMPL(x) #x
#define AGENT_SDK_STRINGIFY(x) AGENT_SDK_STRINGIFY_IMPL(x)

#define AGENT_SDK_VERSION_STRING \
  ("v" AGENT_SDK_STRINGIFY(AGENT_SDK_VER_MAJOR) "." AGENT_SDK_STRINGIFY(AGENT_SDK_VER_MINOR) "." AGENT_SDK_STRINGIFY(AGENT_SDK_VER_PATCH))
